# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsaleh <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/12/17 18:46:37 by rsaleh            #+#    #+#              #
#    Updated: 2018/12/22 17:30:32 by rsaleh           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CFLAGS	=	-Wall -Wextra -Werror
NAME	=	libftprintf.a
OBJDIR	=	obj/
SRCDIR	=	srcs/
FILES	=	printf.c \
			convert.c \
			char_conv.c \
			flag.c
INCLUDE	=	includes/
SRC		=	$(addprefix $(SRCDIR), $(FILES))
OBJ		=	$(addprefix $(OBJDIR), $(patsubst %.c, %.o, $(notdir $(FILES))))

VPATH	= 	$(shell find $(SRCDIR) -type d)

all: $(NAME)

$(NAME): $(OBJ)
	@make -C libft/
	@cd $(OBJDIR) && ar -x ../libft/libft.a && ar -rc ../$(NAME) *.o
	@ranlib $(NAME)
	@printf "$@ has been created\n"

$(OBJDIR)%.o: $(SRCDIR)%.c
	@mkdir -p $(OBJDIR)
	@gcc -o $@ -c $< $(CFLAGS) -I $(INCLUDE)

clean:
	@make clean -C libft/
	@rm -rf $(OBJDIR)

fclean: clean
	@make fclean -C libft/
	@rm -rf $(NAME)

re: fclean all
